// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tavtforuuptautiyqyvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdnRmb3J1dXB0YXV0aXlxeXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDY1NjEsImV4cCI6MjA2NzM4MjU2MX0.9U2MYMh8FCEhcfmkvQxm7q4m0Hr9sPZb5z5-oAQKVIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});